name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm ci

    - name: Build React App
      run: npm run build

    - name: Check Build
      run: |
        if [ -d "build" ]; then
          echo "Build directory exists. Build successful."
        else
          echo "Build directory does not exist. Build failed."
          exit 1
        fi

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm ci

    - name: Build React App
      run: npm run build

    - name: Clear html folder on remote
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          rm -rf /var/www/html/*

    - name: Copy build directory to remote
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        source: "build"
        target: "/var/www/html"
        strip_components: 1
