name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build React App
      run: |
        npm install
        CI='' npm run build
        

    - name: Clear html folder on remote
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          rm -rf /var/www/html/*

    - name: Copy build directory to remote
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        source: "build/*"
        target: "/var/www/html"


    - name: Print working directory and list files
      run: |
        pwd
        ls -l